### ISSUE TITLE
Unable to select css selector

### ISSUE THREAD

**Issue by 0xda157** [Naezr/userchrome-toggle-extended-2#3]
I can't highlight it to copy the "Selector" item in the preferences. I have to use the Browser toolbox in multiprocess mode to get the text from the div. I'm on Firefox 128.0.3 on Linux.

**Comment by Naezr** [comment]
[Запись экрана от 2024-08-06 09-46-57.webm](https://github.com/user-attachments/assets/eda97d3b-174a-48ca-8d5d-b1b7ccfd21e4)

Just click on it, and it will copy the selector
