### ISSUE TITLE
How to change keybinds?

### ISSUE THREAD

**Issue by 0xda157** [Naezr/userchrome-toggle-extended-2#4]
I have no idea how to change the keybindings, you can't click on the keybindings and there isn't a button anywhere.

**Comment by cashmeredev** [comment]
> I have no idea how to change the keybindings, you can't click on the keybindings and there isn't a button anywhere.

you can here
![image](https://github.com/user-attachments/assets/2d0208e9-3c9b-41fb-b2da-99bc248cfdff)
but since the new update it doesn't work for me. i had custom keybindings with ctrl, shift 1-4 but they do not work

edit:
did a clean new installation for shyfox now the shortcuts work again

**Comment by Naezr** [comment]
Changing keyboard shortcuts is a built-in feature in Firefox. The extension cannot change them on its own.

ShyFox should definitely be updated, because it has switched from visible to invisible characters. The old version of ShyFox does not understand the new symbols, and vice versa.
