### ISSUE TITLE
Latest update removed shortcut bindings

### ISSUE THREAD

**Issue by boiwantlearncode** [Naezr/userchrome-toggle-extended-2#5]
<img width="683" alt="Screenshot 2024-08-06 at 12 42 12 PM" src="https://github.com/user-attachments/assets/1cd746b6-9376-4892-a760-19d5f22bca4f">

The "Hide Sidebar" and 3 other shortcuts were removed and changed to that which is shown above. How do I change it back?

**Comment by Naezr** [comment]
https://github.com/Naezr/ShyFox?tab=readme-ov-file#step-2---configure-extensions

**Comment by boiwantlearncode** [comment]
Ah I see the issue, I haven't updated Shyfox to the latest version. It works now, thanks.
