### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by zaeemali272** [Naezr/userchrome-toggle-extended-2#6]
Hello!
After the latest update the extension just stoped working i did fix the shortcuts. but its just not responding. is there something else i have to do.

**Comment by Naezr** [comment]
If you are using ShyFox, update it as well

**Comment by zaeemali272** [comment]
Ok so i think i changed something in about:config relating to shyfox and that was causing it, i refreshed my firefox and repeated the whole installation process and now its fixed
